# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "endpoint-gen"
version = "0.2.1"
edition = "2021"
repository = "https://github.com/pathscale/EndpointGen/"
description = "Generate Rust code for websocket API endpoints"
license = "MIT"

[dependencies]
# Internal dependencies
endpoint-libs = { git = "https://github.com/pathscale/endpoint-libs.git", tag = "v1.0.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
eyre = "0.6"
convert_case = "0.6.0"
itertools = "0.12"
regex = "1.5.4"
clap = { version = "4.5", features = ["derive", "env"] }
futures = "0.3.30"
rustls-pemfile = "2.1.3"
tokio = { version = "1.39.3", features = ["full"] }
tracing = "0.1.40"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "std"] }
tokio-cron-scheduler = "0.11.0"
dashmap = "6.0.1"
tokio-tungstenite = "0.23.1"
tokio-postgres = "0.7.11"
bytes = "1.7.1"
ethers = "2.0.14"
chrono = "0.4.38"
urlencoding = "2.1.3"
tokio-rustls = "0.26.0"
log-panics = "2.1.0"
postgres-from-row = "0.5.2"
deadpool-postgres = { version = "0.14.0", features = ["serde"] }
secrecy = { version = "0.8.0", features = ["serde"] }
hyper = { version = "1.4.1", features = ["server"] }
kanal = "0.1.0-pre8"
reqwest = "0.12.7"
async-trait = "0.1.81"
parking_lot = "0.12.3"
alloy-primitives = "0.8.0"
hex = "0.4.3"
rust_decimal = "1.36.0"
tracing-appender = "0.2.3"
serde_path_to_error = "0.1.16"
rustls = "0.23.12"
lazy_static = "1.5.0"
tokio-util = "0.7.11"
hyper-util = { version = "0.1.7", features = ["full"] }
ron = "0.8"
walkdir = "2.5"
